### ISSUE TITLE
大神，请问能更新实现一下批量下载用户所有笔记吗？而不是单个笔记，谢谢

### ISSUE THREAD

**Issue by dongsenlin** [daxiongpro/spiders#2]
您好，发现这个项目： https://github.com/Crush0/XHS-Scrapy  能实现批量下载用户所有图片视频，但是下载下来的图片有水印logo😂，要是能实现批量且无水印就完美了

**Comment by daxiongpro** [comment]
你好 ，我的是批量下载所有图片，视频爬取应该也是相同原理。代码简单的，稍微研究以下就好啦

**Comment by dongsenlin** [comment]
> 你好，我的是批量下载所有图片，视频下载应该也是一致的原理。代码简单的，稻微研究下面就好啦

谢谢您的耐心回复，我刚才重新试了一下，urls输入用户主页地址，运行后提示：KeyError: 'imageList'。前面可能我没表述清楚😂，就是输入指定的单篇笔记的url确实能批量下载单篇笔记的所有图片。但不能一次性批量下载用户所有笔记。我想请问怎样输入地址或者修改代码才能实现这个功能，，万分感谢

**Comment by dongsenlin** [comment]
您好，我刚刚尝试了同时输入多个笔记地址可以实现，想问下能不能像我提供的那个项目一样，输入用户主页地址就可以实现批量下载所有笔记图片，多有打扰，麻烦您方便的话指教或者更新一下代码，不胜感激🙏

**Comment by daxiongpro** [comment]
打开同一个作者的主页，点开他的不同笔记，你会发现笔记的网址，只有最后一串数字不一样。你稍微改下代码，for循环遍历一下，就可以了。 @dongsenlin

**Comment by dongsenlin** [comment]
> 打开同一个作者的主页，点开他的不同笔记，你会发现笔记的网址，只有最后一串数字不一样。你稍微改下代码，for循环遍历一下，就可以了。 @dongsenlin

好的非常感谢您，我对写代码还不太了解，期待您的更新😄
